[workspace]
members = [
    "app/bot",
    "app/player",
    "crates/config",
    "crates/database",
    "crates/ipc",
    "crates/spotify",
    "crates/shared",
]
resolver = "2"
package.version = "2.3.0"

[patch.crates-io]
audiopus_sys = { git = 'https://github.com/sevenc-nanashi/audiopus_sys', rev = '00e9d16' }
cmake = { git = 'https://github.com/rust-lang/cmake-rs', rev = "6e68d9c" }                 # Temporary workaround on Windows
